### ISSUE TITLE
Feature Request: .pak patcher

### ISSUE THREAD

**Issue by Skyyblaze** [VitaSmith/gust_tools#1]
First of all thanks for the great tools VitaSmith! As someone who just got into Atelier modding to replace the XBOX button-prompts with PS4 ones your tools made things far easier, especially the .pak repacking so you don't have a ton of loose files in the game folder which also helps when the game gets an official update.

That said would it be possible for you to implenent something like a .pak patcher? So for example I could point gust_pak to mainfont00_hd1080_0.g1t aswell as PACK00_04_01.PAK  and it will automatically inject the .g1t file.

I ask because, while it's no problem for me to unpack, replace and repack my own files, I would like to share my controller icon mods and I fear this process might be a bit of a hindrance for the average, less tech-savvy user. A patcher would make things somewhat easier.

I know I could work around this with batch files I suppose but there's still a bit that can go wrong with them.

**Comment by scese250** [comment]
Use Xdelta, it tested with PAK files and it worked.

**Comment by VitaSmith** [comment]
Sorry, I don't think I want to add the feature requested above. If you need to automate patching, I will respectfully ask that you write your own scripts, as I'm way too busy to have time to make these utilities more user-friendly.
