### ISSUE TITLE
gust_enc.exe returns 'main[1] (0xcb53) is not prime' error when decrypting A21 files

### ISSUE THREAD

**Issue by pmcthor777** [VitaSmith/gust_tools#10]
I'm trying to mod some text strings for Atelier Ryza. But when I use gust_enc.exe after modifying the gust_enc.json file "seeds_id" to "A21", I get 'main[1] (0xcb53) is not prime' error.

To clarify, this is on v1.04.

**Comment by VitaSmith** [comment]
Thanks for the report. There was a small bug in the prime validation that I have now fixed.
Please try v1.12 of gust_tools.
Note that you can disable prime validation by setting `"validate_primes"` to `false` in `gust_enc.json`.

**Comment by pmcthor777** [comment]
Thanks! v1.12 works perfectly!
