### ISSUE TITLE
.bsb and. .dat files

### ISSUE THREAD

**Issue by makc-ar** [VitaSmith/gust_tools#14]
Add support for [these files](https://github.com/VitaSmith/gust_tools/files/4641238/bsb.and.dat.files.zip)?

**Comment by VitaSmith** [comment]
Unless someone can provide a description for the structure of the these files, with the fields being used by each record, I don't think I'm going to bother.

**Comment by VitaSmith** [comment]
Okay, I'm going to close this issue then.
