### ISSUE TITLE
Incorrect assumption for field purpose in Elixir Header

### ISSUE THREAD

**Issue by yretenai** [VitaSmith/gust_tools#16]
`version` of `lxr_header` is not version, it's filename width.
I have found elixir files with version 0, 1, and 2, the only change in the format is `lxr_entry.filename` changes size (`0x20 + (lxr_header.version << 4)`).

0: 0x20
1: 0x30
2: 0x40

**Comment by VitaSmith** [comment]
Thanks for the report. I'll try to update the code according to this information when I have a chance.

**Comment by VitaSmith** [comment]
This should be fixed now.
