### ISSUE TITLE
A11-A14 .PSSG.GZ support?

### ISSUE THREAD

**Issue by NikoofDeath** [VitaSmith/gust_tools#17]
I was looking into possibly upscaling some of Atelier Rorona DX's textures, however, unfortunately the majority of its textures (as well as those for Totori, Meruru, and Ayesha) are contained in PSSG.GZ, before they moved to the Elixir format with Escha and Logy. I haven't found any working tools (only brief investigations/requests) for the format, and standard PSSG tools do not work. Would it be within the scope of this project to add support for these files?

**Comment by VitaSmith** [comment]
> Would it be within the scope of this project to add support for these files?

If someone else want to submit a patch, then yes.
If I'm the one that has to do it, then I'm afraid not...

**Comment by CatClawed** [comment]
Is there something Ego PSSG Editor isn't doing for you? It seems to read and extract these files properly, though I can't comment on repacking.

The ones that are just PSSG files were a pain to me (these contain G1T files and Ego doesn't know how to mass extract these textures), so I made a very [janky too](https://github.com/CatClawed/pssg-g1t-extractor) to mass extract them.

**Comment by VitaSmith** [comment]
I'm going to close this issue then, as I'm hoping it is solved with the comment above.
