### ISSUE TITLE
Native Support for GT1 files

### ISSUE THREAD

**Issue by NikoofDeath** [VitaSmith/gust_tools#18]
In looking into modding some non-gust Koei games (Dragon Quest Heroes II and Builders 2 in this case, but potentially others as well), I found that the texture format gt1 was suspiciously similar in name to the g1t textures used in gust's games. While gust_g1t didn't accept them because it checks the extension of its files, simply changing the extension to g1t got it working (seemingly) perfectly. Obviously, not being gust games, these aren't exactly in the scope of this project, but I think it would make sense for gust_g1t to accept gt1 files as well (assuming there isn't some incompatibility that isn't clear to me).
[Here are two example files, and their extracted forms, (2e4 from Dragon Quest Builders 2, 21c from Heroes II) for testing purposes](https://files.catbox.moe/yq1pm3.zip)

**Comment by yretenai** [comment]
DQH2 and DQB2 are Koei games, just licensed by Square.

Whatever you used to extract the textures erroneously called the textures GT1 files because of the file signature being GT1G (but it's written/read as little endian so it's G1TG, Graphics 1 Texture Group)

**Comment by VitaSmith** [comment]
Sounds easy enough to add. Will do this in the newly released version.
