### ISSUE TITLE
Atelier Ryza (Switch) .ebm

### ISSUE THREAD

**Issue by wwwklopar** [VitaSmith/gust_tools#19]
Hello! 
I'm currently trying to extract Atelier Ryza in second time just to be sure that this game can be translated by our team to our language. I'm clearly remebmer that v1.11 of your tool during the first extraction was able to extract .ebm files with text. The last v1.18 can't exctract pretty big amound of .ebm files from switch version with "ERROR: Don't know how to handle this type of .ebm file".
Is somethiing crytical was changed during versions that now tool can't support this files?
I'll will add some examples of files. Can you please look at them?
[event_EN.zip](https://github.com/VitaSmith/gust_tools/files/5004049/event_EN.zip)

**Comment by VitaSmith** [comment]
Thanks for the report. This is indeed a regression. It should be fixed now.
