### ISSUE TITLE
gust_g1t skipping 1x1 textures

### ISSUE THREAD

**Issue by DeathChaos25** [VitaSmith/gust_tools#24]
As title says, the tool is skipping 1x1 textures (used for dummy normals in Persona 5 Strikers), meaning not all textures are dumped, making it impossible to repack the G1T again with the tool due to the missing textures.

These textures work fine (and are dumped correctly) by project_g1m noesis plugin.

Here's a sample [G1T](https://cdn.discordapp.com/attachments/785273624109645865/796419308737396826/H0500_Hero_Daily.g1t) (and accompanying [g1m](https://cdn.discordapp.com/attachments/785273624109645865/796419306002448414/H0500_Hero_Daily.g1m) if needed) that has this issue.

Edit: Seems to be mostly unsupported texture format with other Switch RDB games like Hyrule Warriors: Age of Calamity (all of them still work fine with project_g1m).

**Comment by VitaSmith** [comment]
Thanks for the report. This should now be fixed in the current version.
