### ISSUE TITLE
Atelier Sophie PS4 swizzling texture problem

### ISSUE THREAD

**Issue by GrayDZ** [VitaSmith/gust_tools#25]
[PS4_txtr.zip](https://github.com/VitaSmith/gust_tools/files/5825810/PS4_txtr.zip)
PS4 version of Atelier Sophie textures have swizzle.
Can you help?

**Comment by GrayDZ** [comment]
The problem was resolved. Sorry for disturbing.

**Comment by VitaSmith** [comment]
I've actually added support for type `0x62` in the latest version of `gust_g1t`. For instance this is how your first texture is being decoded in the new version:

![000_good](https://user-images.githubusercontent.com/32225969/105632689-734ec680-5e4c-11eb-9d49-27ed994b4169.png)

Please feel free to ask for texture support. I definitely can't promise I will add them all, but you never know... 😉
