### ISSUE TITLE
New .ebm

### ISSUE THREAD

**Issue by LinkOFF7** [VitaSmith/gust_tools#28]
In Ryza 2 some .ebm files don't have a first 4 bytes with entires number. There is looks lyke `DE FF FF FF`.

**Comment by VitaSmith** [comment]
I'm going to need you to provide the path of one such file, and which `.pak` it was extracted from. Thank you.

**Comment by LinkOFF7** [comment]
Something like that: Data/PACK01.PAK//data\event\en_ev\mm01\
In mm00 ebm files is normal.

**Comment by VitaSmith** [comment]
This should work with the latest version.
