### ISSUE TITLE
1.29 repack issue

### ISSUE THREAD

**Issue by DNMock** [VitaSmith/gust_tools#30]
Moving the X64 folder down out of the data folder and attempting to repack as per the readme leads to an inability to repack.  leaving it in the created data folder allows it to repack, however causes CTD in Ryza 2.  
![gust_tool](https://user-images.githubusercontent.com/78313387/106391103-3c7b3200-63b1-11eb-9e93-bb0683f6b2d2.png)

**Comment by VitaSmith** [comment]
> and attempting to repack as per the readme

The readme says nothing about repacking.

For repacking, you should of course revert whatever operation you did where you altered the content location. Also the example from the readme is for _Blue Reflection_. There's no guarantee that the example given applies as is to other game.

I'm afraid there is nothing to fix here. You just need to make sure that, if you unpack some content, and then move it around, you move it back to where it was before repacking.

**Comment by DNMock** [comment]
Ah, my apologies, I assumed Blue Reflection was just being used as an example of proper repacking methodology rather than as an outlier.
