### ISSUE TITLE
G1t repack issue

### ISSUE THREAD

**Issue by DNMock** [VitaSmith/gust_tools#32]
![G1t](https://user-images.githubusercontent.com/78313387/106854976-d416a400-6681-11eb-82d7-cca0b1a8c183.png)

When re-packing a folder to .g1t format then extracting it the file comes out like the bottom one.  Using 1.30.  File format is DDS compressed to DXT5.

**Comment by VitaSmith** [comment]
Can't help you unless you attach the problematic file, or tell us precisely where it is (what game, what PAK, and complete path to the `.g1t` file in the archive). Thank you.

**Comment by VitaSmith** [comment]
Closing on account that not enough data was supplied to look into the issue.
