### ISSUE TITLE
can't repack files for use in Atelier Ryza 2

### ISSUE THREAD

**Issue by BanaKori** [VitaSmith/gust_tools#33]
basically, I get as far as dropping the files I want into the character folder, and no matter which gust EXE I try, it never seems to wanna repack the files. not sure what I am doing wrong.

**Comment by VitaSmith** [comment]
If you try `.exe` at random, it will of course not work.

To repack, the content of a directory must match exactly the content that was extracted. and you must drop the `.json` file that was created during extraction (you can't just drop a directory on top of `gust_pak.exe` and expect that to work, it must be the `.json` file that was created from a previous unpak).
