### ISSUE TITLE
Gust tools stop when trying to create a folder when there's a special character in the folder path.

### ISSUE THREAD

**Issue by gorzius** [VitaSmith/gust_tools#34]
Looks like the tools stop on the folder creation step when there's a character from the non-english alphabet in the folder path the unpacked file is in. (E.g. Japanese characters or characters with diacritics, like á, é, ű)
The gust_pak gives an error message on this, but all the other tools simply seem to stop.

![gust error](https://user-images.githubusercontent.com/6652568/111041038-83d7f200-8436-11eb-9c72-ec9d3c773594.png)

**Comment by VitaSmith** [comment]
Sorry about that. This should be fixed in the version that was just released.
