### ISSUE TITLE
Issue with gust_pak and Ciel Nosurge DX

### ISSUE THREAD

**Issue by Sugoidude** [VitaSmith/gust_tools#35]
When unpacking, the size of the unpacked directory is lower than the .pak; however, the size on disk is still higher. When packing it back together, it stops at 1.76MB, indicating a read error on facemotiondata.bin, sized at 0KB. Multiple files are sized at 0KB. When trying to unpack this faulty .pak, it gets identified as A17 format. Used PACK01.pak for this. PACK02.pak unpacks, but when packing it back together, it doesn't start and indicates an error: "A22 extensions can't be used on 64 bit PAKs"

**Comment by Sugoidude** [comment]
Attached is PACK01.pak

**Comment by VitaSmith** [comment]
Thanks for the report. This should be fixed in the latest version.
