### ISSUE TITLE
EBM CONVERTER

### ISSUE THREAD

**Issue by foubou** [VitaSmith/gust_tools#36]
Hi VitaSmith, congratulations and thank you very much for your awesome tools ! I really enjoy doing fan translations (I am currently translating Trails in the Sky) but Gust games are in my to-do list.

I would like to know if it is possible for you to make a tool that converts EBM <-> XLS or JSON <-> XLS ?

That'll be great because spreadsheets are for me the best way to translate games.
XLS files allow me to work on the game files with my teammates on Google Drive.

**Comment by VitaSmith** [comment]
Sorry but I just don't have the resources to fulfil what is essentially a personal request. You will have to figure out your own conversion process, as it is unlikely that you will find someone willing to sort this out for you, especially for free...

**Comment by foubou** [comment]
My apologies, I really thought it was something you could do very easily. I thought you would just have to modify your EBM<->JSON converter so that it would have been compatible with XLS files.
I'll try to find another solution ! Thank you :)
