### ISSUE TITLE
gust_elixir fails to extract cf01_09020.elixir.gz

### ISSUE THREAD

**Issue by rty70** [VitaSmith/gust_tools#37]
I'm currently using gust_elixir v1.32 to extract some elixir archives from the file PACK00_02.PAK of Atelier Ryza 2 (which I previously unpacked with gust_pak v1.32). This works well with all the archives I tried but the one I mention in the title, which instead fails to extract and gives the error `ERROR: Can't decompress stream at position 00000000`. I briefly debugged the code and I see it fails inside `tinfl_decompress_mem_to_mem`, because `tinfl_decompress` ultimately returns `TINFL_STATUS_HAS_MORE_OUTPUT`.

**Comment by rty70** [comment]
[cf01_09020.elixir.gz](https://github.com/VitaSmith/gust_tools/files/6341846/cf01_09020.elixir.gz)

**Comment by VitaSmith** [comment]
This should be fixed in the version that was just released.
