### ISSUE TITLE
Issue with Atelier Sophie DX DigitalArtBook

### ISSUE THREAD

**Issue by trails-game** [VitaSmith/gust_tools#39]
For certain g1t files, it seems the DDS images extracted are not displayed correctly:
![image](https://user-images.githubusercontent.com/69129794/116645581-2810ec00-a944-11eb-9e58-3140091e574f.png)

The g1t files are extracted from PACK_ARTBOOK_00_01.PAK and here is one sample file (data\x64\res_cmn\ui\book_dab_sophie_chapter3_030.g1t):
[book_dab_sophie_chapter3_030.zip](https://github.com/VitaSmith/gust_tools/files/6402884/book_dab_sophie_chapter3_030.zip)

**Comment by VitaSmith** [comment]
Thanks for the report. Will look into it when I get a chance.

**Comment by trails-game** [comment]
> Thanks for the report. Will look into it when I get a chance.

Thanks for making and maintaining this great tool.

**Comment by VitaSmith** [comment]
Should be fixed now:

![000](https://user-images.githubusercontent.com/32225969/116945562-e51a8580-ac6f-11eb-9095-49b810e41b9e.png)
