### ISSUE TITLE
gust_enc generating corrupted file

### ISSUE THREAD

**Issue by marcussacana** [VitaSmith/gust_tools#40]
The gust_enc created a xml.e file that crash the game and when I try extract it again, I get the error: `ERROR: Glaze decompression overflow`

[Sample.rar.zip](https://github.com/VitaSmith/gust_tools/files/6489135/Sample.rar.zip)

**Comment by VitaSmith** [comment]
Thanks for the report. I'll look into it when I get a chance.

**Comment by VitaSmith** [comment]
I believe this should be fixed now.
