### ISSUE TITLE
Missing text in .e file

### ISSUE THREAD

**Issue by robotnick83** [VitaSmith/gust_tools#42]
Hello. I'm trying to translate Fairy Tail game to my language and I used gust_enc tool to decode MASTER\ENG\fixed_data\message.xml.e file

But there is a lot of missing text I can't find in that file like this one: https://i.ibb.co/Z19C0Zs/Escena-Fairy.jpg

Please can you help me? Maybe there is some issue with gust_enc and the .e file?

Thank you!

**Comment by VitaSmith** [comment]
> Maybe there is some issue with gust_enc and the .e file?

Sorry but there's just no possibility of `gust_enc` decrypting and decompressing only part of the data, so what you get from `gust_enc` is everything there is, nothing more, nothing less.

The reason for that is that `.e` are both compressed and encrypted, so if we were missing even a single bit during extraction, decompression and decryption would produce an error, as they simply can't work on partial content.

I'm afraid you will have to look elsewhere for the missing text. Some of it may actually reside in the executable.
