### ISSUE TITLE
Compiling gust_ebm.c fails due to comparing unsigned and signed int

### ISSUE THREAD

**Issue by sbruder** [VitaSmith/gust_tools#44]
GCC 10.3.0 on NixOS 21.05 fails to compile `gust_ebm.c` with the following error:
    
    gust_ebm.c: In function ‘main_utf8’:
    gust_ebm.c:85:49: error: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Werror=sign-compare]
       85 |         if (json_array_get_count(json_messages) != abs(nb_messages)) {
          |                                                 ^~

This is fatal because the Makefile specifies `-Wall` (which includes `-Wsign-compare`) and `-Werror` which turns it into an error.

A workaround is the following patch to cast the return value of `abs()`, which should be positive, into an `unsigned int`:

```patch
diff --git a/gust_ebm.c b/gust_ebm.c
index 35ca4f2..7a4cf51 100644
--- a/gust_ebm.c
+++ b/gust_ebm.c
@@ -82,7 +82,7 @@ int main_utf8(int argc, char** argv)
             goto out;
         }
         JSON_Array* json_messages = json_object_get_array(json_object(json), "messages");
-        if (json_array_get_count(json_messages) != abs(nb_messages)) {
+        if (json_array_get_count(json_messages) != (unsigned int)abs(nb_messages)) {
             fprintf(stderr, "ERROR: Number of messages doesn't match the array size\n");
             goto out;
         }
```

I did not open a PR with that patch because I am not very experienced in C and don’t know if that patch is a good way to fix this.

**Comment by VitaSmith** [comment]
Thanks for the report and the patch. I have applied it.
