### ISSUE TITLE
PS4 texType 0x60 (PS4 DXT1) 

### ISSUE THREAD

**Issue by RebootRevival** [VitaSmith/gust_tools#45]
You might take a look and this.  I still don't understand all the DDS encoding however, if you remove the "supported = false" and replace it with "swizzled = true", at line 797, you get a visibly clean file. 
For me, I only need a clean image that I can modify and repackage to PS3, so this is fine for me.  
Just wondering if there is something I am not seeing by doing this.

[PS4-DXT1-extracted.zip](https://github.com/VitaSmith/gust_tools/files/6995382/PS4-DXT1-extracted.zip)
[PS4-DXT1-g1t.zip](https://github.com/VitaSmith/gust_tools/files/6995383/PS4-DXT1-g1t.zip)

Thanks.

**Comment by VitaSmith** [comment]
Thanks. I tested your suggested code changes against the `.g1t` files and they look good for me.
I will release a new version of gust_tools that adds support for type `0x60` textures.
