### ISSUE TITLE
*.G1N Nioh 2 PC

### ISSUE THREAD

**Issue by romhackingvn** [VitaSmith/gust_tools#46]
Could you support Nioh 2? I tried to unpack G1N files, but not success, it's texture's font format. Will be great if this could be supported. Thanks!
[G1N.zip](https://github.com/VitaSmith/gust_tools/files/7087748/G1N.zip)

**Comment by VitaSmith** [comment]
I'm afraid I have no plan to look into `.g1n` unpack/repack. This'll have to come from somebody else.
