### ISSUE TITLE
g1t files ! DDS broken after edition

### ISSUE THREAD

**Issue by foubou** [VitaSmith/gust_tools#47]
Hello !

I want to edit the images of Blue Relection. So I extracted some g1t files and obtained DDS files.
So far, so good.
I tested some modifications with logo_gust.g1t : 
[logo_gust.zip](https://github.com/VitaSmith/gust_tools/files/7144726/logo_gust.zip)

The path of that file is BLUE REFLECTION\DATA\data\x64\res_en\ipu.
It belongs to PACK00_04_1.

My PhotoShop 2020 is unable to read the DDS files generated by gust_g1t converter so I am using GIMP.
Here is a screenshot of my modification in GIMP.
![DDS edited with GIMP](https://user-images.githubusercontent.com/26176310/132876510-af1b8a43-1113-4d0e-b48c-ada79c6b3dc6.png)

And here is how it is displayed in-game.
![logo gust bug](https://user-images.githubusercontent.com/26176310/132876543-0503f039-daec-42ce-8db0-2129bc1964dd.png)

As you can see, the image is broken once implemented in the game.
I also noticed that the size of the DDS is much bigger after being edited with GIMP.

I don't know why.

When I open a DDS file in GIMP, I am always asked to select some options, but the result is the same whatever the options I choose.
![options](https://user-images.githubusercontent.com/26176310/132876615-6fe20add-60ed-4d70-9f8c-fbbe44f36e36.png)

Other options appear when I try to save a DDS file with GIMP.
![options2](https://user-images.githubusercontent.com/26176310/132876637-9c6ed680-b64a-4151-83d7-97ab3b9cf5c8.png)

Can someone help me understanding what I should do to edit the DDS properly without breaking them please ?
Thanks for the help !

**Comment by VitaSmith** [comment]
The lack of responses should indicate that this is probably not the best place to post this question.

Personally, I am using Visual Studio 2019 to view `.dds` files, but its editing capabilities might not be what you are after.

At any rate, I will close this issue, as I would prefer if this issue tracker was only used to report problems related to using gust_tools. If you need help with modding Gust games, there exist public games modding forums, where you should be able to post these kind of questions and get some answers.

**Comment by foubou** [comment]
Got it, thanks !
