### ISSUE TITLE
can you use your tool to edit save files 

### ISSUE THREAD

**Issue by pauljames80** [VitaSmith/gust_tools#55]
hello wondering if its possible to use your tool to edit save files. I got a save file for blue reflection second light. Its exported from switch so don't know how different it is to pc version. I have have done some memory editing so the item stats should be 99 for most items, the 3 characters levels are 50 and total exp they each have is 226836
[data.zip](https://github.com/VitaSmith/gust_tools/files/8015138/data.zip)

**Comment by VitaSmith** [comment]
I'm afraid I have no plans to look into editing save files. These utilities are aimed mostly at modding Gust games and primarily on PC, so editing save files on non PC platforms in order to "cheat" is out of scope of what I am planning to support. Sorry.
