### ISSUE TITLE
Save Data decryption/encryption tools

### ISSUE THREAD

**Issue by sifiro** [VitaSmith/gust_tools#67]
Hi, I would ask for a request to add a decryption/encryption save data tools or some recommendations about known Gust's encryption/decryption algorithm/keys/cipher.

Context: A few days ago, I jailbroke my PS4 to extract unencrypted save data (with the PS4 FileSystem? Standard Encryption) to import it into my PC Saves. Attempting to import my Blue Reflection save data I noticed that the Userdata from PC is unencrypted and PS4 encrypted, checking the SystemData of PS4 and PC both are encrypted and the PS4 System Save loads successfully on the PC Game version but It can't load encrypted UserData.

plus my case (And maybe Atelier Sophie and Firis same case?), this could be a good addition for the creation of save data editor tools.

I attached the PS4 and PC SaveData If that can help you 
(I don't think the save data has copyright, but If I broke some rules, I would delete them)
[BR1_Savedata.zip](https://github.com/VitaSmith/gust_tools/files/9283659/BR1_Savedata.zip)

Greetings

**Comment by VitaSmith** [comment]
Not gonna happen.

First of all, it's only in movies (or if someone uses a very lousy encryption algorithm, which, over the last 10 years, nobody does any more) that someone may look at a dataset containing the encrypted and decrypted version of the same data, and derive the encryption algorithm. It's just not how that works. Instead, if you want to figure out a decryption algorithm, you need to run a debugger against the application while it decrypts the data, and this process is so time consuming that it's something you only ever do if the encryption algorithm is super important to you... which I'm afraid the data save encryption algorithm of the PS4 isn't.

If someone wants to send a patch, I'll take it. But I'm definitely not going to be the one wasting part of my life trying to break an encryption I don't care about, sorry.
