### ISSUE TITLE
Images are all purple?

### ISSUE THREAD

**Issue by CherriCola** [VitaSmith/gust_tools#68]
So I just went through a bunch of g1t files and realized that they all came out Purple? Is there a reason for this or a way to fix it? I've never used this before so please forgive me if this has an obvious fix.

![000](https://user-images.githubusercontent.com/44213648/183746414-9840bff9-497d-48c0-9c48-a2be6b71bdc7.png)

**Comment by VitaSmith** [comment]
> Is there a reason for this or a way to fix it?

I'm afraid I can't help you unless you do provide the `.g1t` where these images are.
Please understand that developers can't _guess_ what an issue is, or how to fix it, unless they have access to the same __data__ as the one you used...

**Comment by CherriCola** [comment]
> 

I actually figured it out, Just forgot to close the issue. My apologies.

**Comment by Chubby-Bub** [comment]
> > 
> 
> I actually figured it out, Just forgot to close the issue. My apologies.

Do you, by chance, remember the solution to this?
![ed23444e_000](https://github.com/VitaSmith/gust_tools/assets/65587508/890083e0-053f-45d7-877b-3b5f49443754)
 I am having the same issue. In fact, with the same game, _Persona 5 Strikers_. Included is the same g1t file.
[ed23444e.zip](https://github.com/VitaSmith/gust_tools/files/14881824/ed23444e.zip)
