### ISSUE TITLE
Feature request: Add a "gust_g1m" tool to unpack/repack any G1M file that contains meshes, bones, etc

### ISSUE THREAD

**Issue by Jupisoft111** [VitaSmith/gust_tools#71]
Hello and thanks for your awesome tool. I'm using it to mod Fatal Frame 5 Maiden of Balck Water, but I believe that a tool that somehow could either extract all the contents of a G1M file might help me make mods to the meshes.

It would be better of course if somehow it could export the G1M file to a blender compatbile format, and once edited there, repack it again into the G1M file, but I guess that would be too much to ask for? If that's the case, then at least having a tool that can unpack and repack the different parts a G1M file has will also be useful.

And by the way do you know of any source of information I could read to better understand the G1M format in case I want to make a tool to convert it to a blender compatible format? Becasue I can't seem to find any information online about the G1M format...

Thanks a lot in advance and congratulations once again for your awesome tools, because they allowed me and others to properly edit the game textures and even some of the meshes for simple files. Have a wonderful day :-)

**Comment by VitaSmith** [comment]
Obviously, I too considered it, but after looking into what would be required to produce such a conversion tool that I'd consider worthy of being included into gust_tools, I found that the amount of work required is just way more than I am willing to invest.

So I can tell you with absolute certainty that the only way you're ever going to have a g1m ↔ blender in gust_tools is if somebody else invests their own time to do it and submits a Pull Request, as it won't be coming from me.
