### ISSUE TITLE
Editing NPC speechs for Sophie 1 DX

### ISSUE THREAD

**Issue by Schneitizel** [VitaSmith/gust_tools#72]
Hi!
I would like to edit the NPC dialogues in the first Atelier Sophie game (The DX version)
Your tool allows me to open the .pak files and get .e and .xml files, but if I edit the dialogues in these files and go backwards, nothing changes
On the contrary, if I modify the fm_data_npc.dat file ("Rumors" become "0umors" for example), the game displays my modifications
Modifying the .dat file is not practical, and I don't really want to modify the length of such a file

Here is the .dat file in question with my modification, plus a screenshot

Thanks for your help!
![image](https://user-images.githubusercontent.com/24242526/227112210-92e69a57-aedb-48e3-927b-35a23a26bf48.png)

[fm_data_npc.zip](https://github.com/VitaSmith/gust_tools/files/11047268/fm_data_npc.zip)

**Comment by VitaSmith** [comment]
I'm afraid I'm not planning to add support for `.dat` files at this stage. You will have to create your own `.dat` editor or ask somebody else. Sorry.
