### ISSUE TITLE
Atelier ryza (translate) to french (.xlm and .ebm) 

### ISSUE THREAD

**Issue by 1vierock** [VitaSmith/gust_tools#73]
Hi, :)

I need some help, because I translated a part of the game with the Gust tool the .xlm and .emb but in the game nothing is changed, is there any step left that I have forgotten please?

**Comment by VitaSmith** [comment]
Possibly, this is the same as #72 and you need to edit a different file. Or, if you did see the dialog you wanted to edit in the `.json`/`.ebm` and it doesn't appear in the game after you modified it, it means you did not replace/repack the right files.

Please bear in mind that, if a `.xml` and `.xml.e` exist, it's most likely the the `.xml.e` that you need to modify, as the `.xml` is **not** actually used by the game engine but is just there as a duplicate.

At any rate, I would suggest that you post this kind of question to mod support forums, which this issue tracker does not substitute as, as it's only there to address issues that are found when using the utilities.
