### ISSUE TITLE
Failed to unpack PACK00_02.PAK of Atelier Ryza 3

### ISSUE THREAD

**Issue by fioredio** [VitaSmith/gust_tools#74]
PACK00_02.PAK of Atelier Ryza 3 (steam) cannot be extracted with v1.53 gust_pak.exe.
There are no error messages, but just a file named "^ZTVAddC" is created in the same folder.

**Comment by bigbenzh** [comment]
It seems that Ryza 3 is using a new encryption? 
The name "^ZTVAddC" is actually filename detected by gust_pak.exe for all the files inside PAK archive (you can see size changes during the extraction), which is definitely not correct, 

and the output files are not in recognized format ( at least I could not find g1t format files in image archive PACK00_01.PAK)

Might have to wait for the update

**Comment by VitaSmith** [comment]
That's expected. Newer Atelier games use a [per-game decryption master key](https://github.com/VitaSmith/gust_tools/blob/6ac4c5c2e1418d93d5785b78c045bfa2f5d8d49c/gust_pak.c#L73-L87) that needs to be added to `gust_pak`.

Please use `gust_pak` version 1.54 or later to unpack Atelier Ryza 3.
