### ISSUE TITLE
(SWITCH) ERROR: Texture array with a factor of 2 doesn't match our assertion

### ISSUE THREAD

**Issue by doax3glitcher** [VitaSmith/gust_tools#77]
TYPE OFFSET     SIZE       NAME             DIMENSIONS MIPMAPS PROPS
ERROR: Texture array with a factor of 2 doesn't match our assertion
Please report this error to https://github.com/VitaSmith/gust_tools/issues.

[NORM.zip](https://github.com/VitaSmith/gust_tools/files/11157617/NORM.zip)

**Comment by VitaSmith** [comment]
This should be fixed in the latest version (though I am not completely sure that doubling the height of these textures is the right thing to do).
