### ISSUE TITLE
Nights of Azure PC

### ISSUE THREAD

**Issue by Smash0251** [VitaSmith/gust_tools#78]
Im trying to use the program to extract the files from it but it keeps popping up an error for me. Idk if im just not doing it right but It keeps giving me this error. Please Help

My Discord is Tatsuya#8383 if you wanna help me there

![image](https://user-images.githubusercontent.com/53153501/231653509-acef1710-4d72-4bdd-8c9c-be26e3c58fd3.png)

**Comment by Smash0251** [comment]
![image](https://user-images.githubusercontent.com/53153501/231837987-54afba68-dd3e-4a67-bac4-dd2c56ce5d06.png)
 Ok got it working but for the models, which program do I need to view em or convert them to 3D objects

**Comment by VitaSmith** [comment]
Since nobody answered here, you will need to do your won research or ask that question elsewhere, as these utilities are just for content extraction, not model viewing or converting.
