### ISSUE TITLE
gust_g1t fail to pack due to SSE4.2 requirement which is higher than the game itself

### ISSUE THREAD

**Issue by avril-gh** [VitaSmith/gust_tools#8]
**version**
Gust Tools v1.9

**issue**
gust_g1t can unpack a test file but it **fail to pack** it back
This is because tools require SSE4.2 which are higher requirement that the games itself,
therefore **hardware which may run the games successfully cannot run tools for it**.

**Comment by VitaSmith** [comment]
Thanks for the report. Can you please describe the error you are getting?

I tried to recreate the issue with the file you attached, but everything seems to work just fine for me, and the recreated `.g1t` is binary identical to the original file. I tried both by using the command line (see below) as well as dropping the extracted `pc00f_model` folder, using the same binaries as the one I released:
```
C:\Projects\gust_tools>gust_g1t pc00f_model.g1t
Extracting 'pc00f_model.g1t'...
TYPE OFFSET     SIZE       NAME                DIMENSIONS MIPMAPS SUPPORTED?
0x59 0x000000ac 0x002a0014 pc00f_model\000.dds 2048x2048  3       YES
0x59 0x002a00c0 0x002a0014 pc00f_model\001.dds 2048x2048  3       YES
0x59 0x005400d4 0x002a0014 pc00f_model\002.dds 2048x2048  3       YES
0x5b 0x007e00e8 0x00540014 pc00f_model\003.dds 2048x2048  3       YES
0x59 0x00d200fc 0x0002a014 pc00f_model\004.dds 512x512    3       YES
0x59 0x00d4a110 0x0000a814 pc00f_model\005.dds 256x256    3       YES
0x5b 0x00d54924 0x00005414 pc00f_model\006.dds 128x128    3       YES
0x59 0x00d59d38 0x0000001c pc00f_model\007.dds 4x4        1       YES
0x59 0x00d59d54 0x000a8014 pc00f_model\008.dds 1024x1024  3       YES
0x59 0x00e01d68 0x0000001c pc00f_model\009.dds 4x4        1       YES
0x59 0x00e01d84 0x000a8014 pc00f_model\010.dds 1024x1024  3       YES
0x59 0x00ea9d98 0x0000001c pc00f_model\011.dds 4x4        1       YES
0x59 0x00ea9db4 0x0002a014 pc00f_model\012.dds 512x512    3       YES
0x59 0x00ed3dc8 0x0000001c pc00f_model\013.dds 4x4        1       YES
0x59 0x00ed3de4 0x0000001c pc00f_model\014.dds 4x4        1       YES
0x5b 0x00ed3e00 0x00054014 pc00f_model\015.dds 512x512    3       YES
0x59 0x00f27e14 0x0000001c pc00f_model\016.dds 4x4        1       YES
0x5b 0x00f27e30 0x00000088 pc00f_model\017.dds 4x4        1       YES

C:\Projects\gust_tools>gust_g1t pc00f_model
Creating 'pc00f_model.g1t'...
Saved backup as 'pc00f_model.g1t.bak'
OFFSET   SIZE     NAME                DIMENSIONS MIPMAPS SUPPORTED?
000000ac 002a0014 pc00f_model\000.dds 2048x2048  3       YES
002a00c0 002a0014 pc00f_model\001.dds 2048x2048  3       YES
005400d4 002a0014 pc00f_model\002.dds 2048x2048  3       YES
007e00e8 00540014 pc00f_model\003.dds 2048x2048  3       YES
00d200fc 0002a014 pc00f_model\004.dds 512x512    3       YES
00d4a110 0000a814 pc00f_model\005.dds 256x256    3       YES
00d54924 00005414 pc00f_model\006.dds 128x128    3       YES
00d59d38 0000001c pc00f_model\007.dds 4x4        1       YES
00d59d54 000a8014 pc00f_model\008.dds 1024x1024  3       YES
00e01d68 0000001c pc00f_model\009.dds 4x4        1       YES
00e01d84 000a8014 pc00f_model\010.dds 1024x1024  3       YES
00ea9d98 0000001c pc00f_model\011.dds 4x4        1       YES
00ea9db4 0002a014 pc00f_model\012.dds 512x512    3       YES
00ed3dc8 0000001c pc00f_model\013.dds 4x4        1       YES
00ed3de4 0000001c pc00f_model\014.dds 4x4        1       YES
00ed3e00 00054014 pc00f_model\015.dds 512x512    3       YES
00f27e14 0000001c pc00f_model\016.dds 4x4        1       YES
00f27e30 00000024 pc00f_model\017.dds 4x4        1       YES

C:\Projects\gust_tools>
```

Maybe this is a path issue?

I know there is an issue with paths that contain a space. For instance dropping a folder from `C:\Projects\gust_tools\` will work but not from `C:\Projects\gust tools\` because that contains a space, and you need to use the command line with quotes then (such as `gust_g1t "C:\Projects\gust tools\pc00f_model"`). Does your path contain a space? Or does it contain non western characters? What happens if you try from a different folder (e.g. `C:\temp`)?

I'll try to fix the issues of spaces with dropped folders when I get a chance, but it might be a bit tricky.

**Comment by avril-gh** [comment]
The issue turns out to be `popcnt` instruction in binary, which is addition to [SSE4.2](https://en.wikipedia.org/wiki/SSE4#SSE4.2) while my CPU supports only SSE4.1

Solution could be to compile it with little lower requirements which should'nt be much hurt for performance while increasing compatibility with hardware that are still on market.

**Should i compile it myself excluding SSE4.2 so it work on CPU's that does not support SSE4.2, or you will release a version without SSE4.2 ?**

**Comment by VitaSmith** [comment]
Thanks for the in depth analysis. I've removed the built in references for v1.10, so it should work on non SSE4.2 CPUs.

**Comment by avril-gh** [comment]
Tested v1.10 seems to work now and there's no crashes. Thank you.
![gust](https://user-images.githubusercontent.com/3224132/72825533-80543b00-3c77-11ea-8ddc-b8e6912892fd.jpg)
