### ISSUE TITLE
Add support decrypt save games

### ISSUE THREAD

**Issue by ikhoeyZX** [VitaSmith/gust_tools#86]
hi, gust tool was good tool, but i need decrypt save games because i wan't play Atelier Sophie from my PC saves to vita3k emulator and my PS Vita also same like emu, the reason why it won't load because PC have special DLC that block save game being loaded to vita3k emulator or PS Vita. It looks like most gust game are encrypted save games but it can loaded to other platform and it will blocked if DLC are installed

![1](https://github.com/VitaSmith/gust_tools/assets/79812109/fb126159-1abb-4c4a-947b-2dfd5a46c2f4)

**Comment by VitaSmith** [comment]
I'm afraid I have no plans to do what you ask. This is too specific a request, and I simply don't have the time.
If someone else wants to invest their own time to look into this, I will accept a patch, but that's about it.
