### ISSUE TITLE
Please update for some files in Winning Post 10 (other files if possible)

### ISSUE THREAD

**Issue by joyingwol** [VitaSmith/gust_tools#87]
Hello there. Here are 2 questions:
# G1t issues
Firstly, in *Winning Post 10*, there are some .fdata files in `Winning Post 10\FPackages\High\release` (also some in `\Winning Post 10\FPackages\Middle\release`)
I use [fdata_dump](https://github.com/DeathChaos25/fdata_dump) to dump the files and come out with some files with .g1f .g1s .g1t format.
Then I use gust_g1t.exe to try to unpack `.g1t` and it showed logs as following:
```
Extracting 'F:\fdata_out\g1t\5BDD3724.g1t'...
TYPE OFFSET     SIZE       NAME             DIMENSIONS MIPMAPS PROPS
ERROR: Cube map with a factor of 256 doesn't match our assertion
```
So if possible you may update it?
G1t files here: <https://drive.google.com/file/d/1C3kmfh_mHKP5B7zPp6oQxPX2lorfw8vx/view?usp=sharing>
# Other Fixed file format
Another question is if there is some possibility to use your tools to unpack the `unb/.unh` files in *Winning Post series*.
From *Winning Post 7*, Koei use a set of files while `.unh` means a hash list or file list of 'united files' (they describe the packed files as united files in a document) , and `.unb` files to contain and compress the required files.
![](https://s2.loli.net/2023/11/18/i7e1NLvH5btWsca.png)

> In Switch version of WP8 2017, they acidentally packaged a file which should not be there...

[DATA.UNH.txt](https://github.com/VitaSmith/gust_tools/files/13398836/DATA.UNH.txt)
Winning Post 8 has a Chinese patch and I am also sure they have successfully unpack the files but I can not make any contact of anyone in the group making the patch 10 years ago.
The patch file is here: <https://drive.google.com/file/d/1BOuXKRYDgcZZB7gadFxOqOGZYmbLUrys/view?usp=drive_link>
Both of the formats are used from WP7 (2008?)  to recent release title WP10 (2023).

I am not sure if you have interest in unpacking these files so I just **try** to open the issue afterall.
If okay, I can also provide with the original version of the games...

**Comment by VitaSmith** [comment]
I'm not planning to ever add support for `unb`/`unh` to gust tools. I just don't have the time for that.

As a matter of fact, I have no idea when/if I'll ever get a chance to look into the problematic `.g1t` you provided, but I'll see what I can do.

**Comment by joyingwol** [comment]
Thank you and I will not continue on this.
